/***
*  $Id$
**
*  File: a6.cpp
*  Created: Apr 08, 2015
*
*  Author: Jaroslaw Zola <jzola@buffalo.edu>
*  Copyright (c) 2015 Jaroslaw Zola
*/

// *** DO NOT EDIT THIS FILE ***

#include "token.hpp"
#include "a6.hpp"

#include <iostream>
#include <vector>

int main(int argc, char* argv[]) {
	std::vector<token> tokens;

	std::string s;
	while (std::cin >> s) tokens.push_back(to_token(s));

	// your code is invoked here
	try {
		double d = RPN(tokens.begin(), tokens.end());
		std::cout << d << std::endl;
	}
	catch (...) {
		std::cout << "error" << std::endl;
	}

	return 0;
} // main
